// app/layout.tsx
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Adnan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${poppins.variable} h-full overflow-hidden`}>
        {/* ✅ ThemeProvider should wrap everything */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="mx-auto max-w-6xl px-4 h-screen">
            <div className="grid grid-cols-[1fr_1px_3fr] gap-4 h-full py-5">
              <div className="h-full overflow-hidden">
                <Sidebar />
              </div>
              <Separator
                orientation="vertical"
                className="bg-gray-200 h-full dark:bg-white/30"
              />
              <ScrollArea className="h-full overflow-auto">
                <div className="flex flex-col h-full">
                  <Header />
                  <main className="flex-1">{children}</main>
                </div>
              </ScrollArea>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
